# fly.toml app configuration file generated for contribhub-api on 2025-08-10T02:41:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'contribhub-api'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
